### ISSUE TITLE
Double check boolean values for all JSON requests

### ISSUE THREAD

**Issue by prioux** [aces/cbrain#862]
We should make sure our JSON outputs produce `true` and `false` and not `"true"`, `"false"`, `"nil"`, `0`, `1`, `""` etc.

1) Fix the controller code
2) Create new SWAGGER spec with a new version number (use my spec on SwaggerHub)

**Comment by natacha-beck** [comment]
Not sure I get understand this issue correctly. 
But I tested all the API call that should return a boolean via the online CBRAIN API and everything seems to be ok (I get a boolean when I should).

**Comment by prioux** [comment]
Don't use the online API, it probably transforms values because it's based on the swagger description and you can't see which is which.

The API does still have many places with confusions, e.g. the `invisible` attribute of Groups is a proper boolean, versus the `hidden` attribute of Userfiles is a fake string one:

Swagger spec:
```yaml
  Group:
    type: object
    properties:
#...
      invisible:
        type: boolean
        description: |
          Specifies whether or not the group is visible to Normal Users.
          Invisible groups exist to specify levels of access to Userfiles,
          DataProviders and Bourreaux.

  Userfile:
    type: object
    properties:
#...
      hidden:
        type: string
        format: boolean
        description: >-
          Boolean variable that specifies whether this file is hidden or not in
          the user interface.
```
